// French reading aids for reviewers. These paraphrases are not evaluation text.
export const INTENTS_FR: Record<string, string> = {
  "LNG-001": "Bonjour, vas-tu bien aujourd’hui ?",
  "LNG-002": "Je vais au marché acheter des fruits et du riz.",
  "LNG-003": "Je voudrais boire de l’eau froide, s’il vous plaît.",
  "LNG-004": "Les enfants jouent dans la cour.",
  "LNG-005": "Maman prépare du pondu et du fufu pour la famille.",
  "LNG-006": "Est-ce que nous nous verrons demain matin ?",
  "LNG-007": "Il a beaucoup plu, donc la route est pleine d’eau.",
  "LNG-008": "Ferme la porte à clé avant de quitter la maison.",
  "LNG-009": "Notre voisin a emprunté une chaise hier.",
  "LNG-010": "Peux-tu me donner un peu de sel ?",
  "LNG-011": "Regarde, le courant est revenu !",
  "LNG-012": "Mon téléphone s’est éteint parce que la batterie est vide.",
  "LNG-013": "Ce bus est plein ; attendons le suivant.",
  "LNG-014": "L’enfant dort ; ne faites pas de bruit.",
  "LNG-015": "Je n’ai pas bien compris ; répète et parle lentement.",
  "LNG-016": "Quelle route mène à la gare ?",
  "LNG-017": "Quand tu arriveras là-bas, appelle-moi immédiatement.",
  "LNG-018": "J’ai trouvé les clés sous la table.",
  "LNG-019": "Elle lave les vêtements et les fera sécher dehors.",
  "LNG-020": "Le chien aboie près du portail.",
  "LNG-021": "Après le travail, je veux me reposer un moment.",
  "LNG-022": "Chacun doit apporter sa propre assiette.",
  "LNG-023": "Pourquoi es-tu en retard ? Y avait-il des embouteillages ?",
  "LNG-024": "Je veux mon thé sans sucre.",
  "LNG-025": "Je me réveille à six heures tous les matins.",
  "LNG-026": "Nettoyons la maison avant l’arrivée des invités.",
  "LNG-027": "Le livreur est venu, mais il n’y avait personne à la maison.",
  "LNG-028": "L’odeur de la nourriture qui vient de la cuisine est agréable.",
  "LNG-029": "Prends le sac sur la chaise, mets-y les affaires des enfants et laisse-le près de la porte.",
  "LNG-030": "Elle a dit : « Attends-moi ici, je reviens vite ! »",
  "LNG-031": "Ouvrez vos livres à la page dix.",
  "LNG-032": "Écris ton nom et lis chaque lettre.",
  "LNG-033": "Quelle est l’idée principale de cette histoire ?",
  "LNG-034": "Tu dois finir les devoirs avant demain.",
  "LNG-035": "Si tu additionnes cinq et sept, quel résultat obtiens-tu ?",
  "LNG-036": "Quand l’eau bout, elle devient chaude et se transforme en vapeur.",
  "LNG-037": "Qui peut répondre à cette question ?",
  "LNG-038": "Compare les deux réponses et montre leurs différences.",
  "LNG-039": "Travaillez par groupes de quatre et partagez vos idées.",
  "LNG-040": "Un mot nouveau est un mot dont nous ne connaissons pas encore le sens.",
  "LNG-041": "Lis cette phrase à voix haute.",
  "LNG-042": "Si tu vois une erreur, corrige-la dans le texte écrit.",
  "LNG-043": "Mets ces événements dans l’ordre où ils se sont produits.",
  "LNG-044": "Donne ta réponse et explique pourquoi tu penses qu’elle est correcte.",
  "LNG-045": "Sur la carte, trouve la rivière qui passe près de la ville.",
  "LNG-046": "L’enseignant a envoyé la leçon sur l’ordinateur de l’école.",
  "LNG-047": "Puis-je poser une question ?",
  "LNG-048": "Répète ces mots trois fois pour t’en souvenir.",
  "LNG-049": "Que s’est-il passé après le vent violent ?",
  "LNG-050": "Si tu ne connais pas la réponse, regarde l’exemple puis essaie seul.",
  "LNG-051": "Ce mot ne se prononce pas de la même façon en lingala et en français.",
  "LNG-052": "Tu as bien travaillé, continue !",
  "LNG-053": "Avant de parler devant la classe, organise tes idées, parle clairement et donne un exemple.",
  "LNG-054": "Mets un point d’interrogation à la fin de la phrase.",
  "LNG-055": "Avec tes propres mots, résume les trois points importants.",
  "LNG-056": "Un jour, un enfant a vu un petit oiseau sur la route.",
  "LNG-057": "Ce soir-là, les nuages ont couvert le ciel et la pluie a commencé.",
  "LNG-058": "Grand-mère a dit qu’elle devait rentrer avant la tombée de la nuit.",
  "LNG-059": "L’homme a ouvert la boîte, a regardé à l’intérieur et a été surpris.",
  "LNG-060": "Mais qui les suivait de loin ?",
  "LNG-061": "Les enfants ont couru jusqu’au grand arbre.",
  "LNG-062": "Ils ont entendu un bruit étrange derrière la maison.",
  "LNG-063": "« N’aie pas peur, a dit son frère ou sa sœur, je suis là. »",
  "LNG-064": "Un petit bateau avançait lentement sur la rivière.",
  "LNG-065": "Elle voulait rester, mais elle a finalement décidé de partir.",
  "LNG-066": "Au lever du soleil, la ville s’est réveillée au bruit des voitures, des vendeurs et des enfants qui allaient à l’école.",
  "LNG-067": "Dans le vieux livre, il a trouvé une photo de leur famille.",
  "LNG-068": "Elle a caché la lettre dans un endroit sûr pour que personne ne la voie.",
  "LNG-069": "Une chèvre a quitté le troupeau et est entrée dans le champ.",
  "LNG-070": "S’ils avaient attendu quelques minutes de plus, ils auraient vu le train partir.",
  "LNG-071": "Soudain, la lumière s’est éteinte et toute la maison s’est retrouvée dans le noir.",
  "LNG-072": "Ils ont cherché l’enfant partout et l’ont finalement trouvé dans la bibliothèque.",
  "LNG-073": "« Je… je ne sais pas », a-t-elle dit doucement.",
  "LNG-074": "Trois jours plus tard, une bonne nouvelle est arrivée.",
  "LNG-075": "La personne âgée a donné un fruit à l’enfant, qui l’a remerciée.",
  "LNG-076": "L’arbre que grand-père avait planté quand il était jeune était devenu grand.",
  "LNG-077": "L’enfant a demandé : « Arriverons-nous là-bas avant le soir ? »",
  "LNG-078": "L’odeur du pain frais lui a rappelé la maison de son enfance.",
  "LNG-079": "Ils pensaient que le voyage était terminé, mais la partie difficile restait à venir.",
  "LNG-080": "À partir de ce jour, ils se sont retrouvés chaque semaine.",
  "LNG-081": "Appuyez sur 1 pour le lingala ou sur 2 pour le français.",
  "LNG-082": "Veuillez patienter ; un agent vous répondra bientôt.",
  "LNG-083": "Donnez votre numéro de commande pour que nous puissions la retrouver.",
  "LNG-084": "Pour protéger votre compte, nous devons confirmer votre nom et votre date de naissance.",
  "LNG-085": "Désolé, votre commande a été retardée.",
  "LNG-086": "Souhaitez-vous un remboursement ou choisir un autre article ?",
  "LNG-087": "Ouvrez le message que nous vous avons envoyé pour changer votre mot de passe.",
  "LNG-088": "Vérifiez si votre appareil est connecté à Internet.",
  "LNG-089": "Fermez l’application, rouvrez-la et réessayez.",
  "LNG-090": "Votre colis a quitté l’entrepôt et est en route vers vous.",
  "LNG-091": "À quelle heure votre bureau ouvre-t-il ?",
  "LNG-092": "Débranchez l’appareil, attendez trente secondes, puis rebranchez-le.",
  "LNG-093": "Votre paiement n’est pas passé ; vérifiez que les informations de la carte sont correctes.",
  "LNG-094": "Pouvez-vous confirmer l’adresse à laquelle nous devons envoyer le colis ?",
  "LNG-095": "Nous vous rappellerons ce soir.",
  "LNG-096": "Nous avons ouvert un dossier d’assistance pour votre problème.",
  "LNG-097": "Gardez ce code ; il vous aidera si vous rappelez.",
  "LNG-098": "Le problème se produit-il tout le temps ou seulement quand vous ouvrez l’application ?",
  "LNG-099": "Merci de nous avoir appelés ; passez une bonne journée.",
  "LNG-100": "Souhaitez-vous être averti par SMS ou par e-mail ?",
  "LNG-101": "Si vous demandez la suppression du compte, vos informations seront supprimées après le délai imposé par la loi.",
  "LNG-102": "Cet article est en rupture de stock, mais il pourrait revenir la semaine prochaine.",
  "LNG-103": "Si le colis est endommagé, prenez une photo et envoyez-la-nous.",
  "LNG-104": "Nous avons reçu votre message, mais nous attendons encore la réponse de la société de transport.",
  "LNG-105": "Après cette conversation, notez notre service de 1 à 5.",
  "LNG-106": "Lavez-vous les mains avec du savon et de l’eau propre.",
  "LNG-107": "Buvez beaucoup d’eau lorsqu’il fait très chaud.",
  "LNG-108": "Si vous avez du mal à respirer, consultez rapidement un professionnel de santé.",
  "LNG-109": "Lisez l’étiquette du médicament et suivez les instructions du professionnel de santé.",
  "LNG-110": "Faites bien cuire les aliments avant de les manger.",
  "LNG-111": "Si un enfant a de la fièvre, surveillez sa température et appelez un professionnel de santé si elle augmente.",
  "LNG-112": "Couvrez votre bouche et votre nez avec votre coude lorsque vous toussez.",
  "LNG-113": "Apportez la carte de vaccination le jour du rendez-vous.",
  "LNG-114": "Si l’eau n’est peut-être pas potable, faites-la bouillir avant de la boire.",
  "LNG-115": "Reposez-vous bien et mangez de façon variée.",
  "LNG-116": "Ne donnez pas un médicament à une personne à qui il n’a pas été prescrit.",
  "LNG-117": "Notez vos questions avant d’aller voir le professionnel de santé.",
  "LNG-118": "Si une personne est inconsciente ou ne respire pas, appelez le numéro d’urgence et suivez les instructions.",
  "LNG-119": "Dormez sous une moustiquaire pour réduire le risque de paludisme.",
  "LNG-120": "Éliminez l’eau stagnante près de la maison.",
  "LNG-121": "Prenez le médicament à l’heure prescrite et ne dépassez pas la dose.",
  "LNG-122": "Si l’inquiétude devient trop forte, parlez-en à une personne de confiance.",
  "LNG-123": "Où se trouve le centre de santé le plus proche ?",
  "LNG-124": "Quand la douleur a-t-elle commencé, et devient-elle plus forte ou plus faible ?",
  "LNG-125": "Êtes-vous allergique à un médicament ou à un aliment ?",
  "LNG-126": "Gardez les médicaments hors de portée des enfants.",
  "LNG-127": "La clinique est ouverte aujourd’hui, mais le service du laboratoire ne commencera que l’après-midi.",
  "LNG-128": "Retournez à l’hôpital si les symptômes ne s’améliorent pas après deux jours.",
  "LNG-129": "Acceptez-vous d’être examiné maintenant par le professionnel de santé ?",
  "LNG-130": "Ces informations sont seulement indicatives ; elles ne remplacent pas un avis médical.",
  "LNG-131": "Tous les articles coûtent 15 750 francs congolais.",
  "LNG-132": "Un billet coûte douze euros et cinquante centimes.",
  "LNG-133": "La personne est née le 3 novembre 1998.",
  "LNG-134": "Votre rendez-vous est le 14 août 2026 à 9 h 30.",
  "LNG-135": "Le train 407 partira à 18 h 45.",
  "LNG-136": "Appelez le numéro belge plus trente-deux, deux, cinq-cinq-cinq, zéro-un, zéro-neuf.",
  "LNG-137": "Le prix a diminué de quinze pour cent.",
  "LNG-138": "La température du corps est de 37,8 degrés Celsius.",
  "LNG-139": "Ce sac pèse 2,75 kilogrammes.",
  "LNG-140": "Elle a économisé vingt-cinq dollars pour le voyage.",
  "LNG-141": "Le projet nécessite un million de francs congolais.",
  "LNG-142": "Le bureau est ouvert de 8 h à 17 h 30.",
  "LNG-143": "Le trajet durera deux heures et vingt minutes.",
  "LNG-144": "Ils ont partagé le pain en deux pour chaque enfant.",
  "LNG-145": "Le bureau se trouve au troisième étage.",
  "LNG-146": "Entrez par la porte 8B.",
  "LNG-147": "Le rapport couvre les années 2024 à 2026.",
  "LNG-148": "Nous avons quarante-huit kilogrammes de riz.",
  "LNG-149": "Il a payé 20 000 francs congolais et reçu 3 500 francs de monnaie.",
  "LNG-150": "La réunion aura lieu le lundi 5 octobre.",
  "LNG-151": "La nouvelle application est la version 2.1.4.",
  "LNG-152": "L’hôpital se trouve à six kilomètres d’ici.",
  "LNG-153": "La table mesure 120 centimètres sur 75 centimètres.",
  "LNG-154": "Cette personne fête aujourd’hui ses dix-huit ans.",
  "LNG-155": "Le taux d’intérêt est de 7,5 pour cent par an.",
  "LNG-156": "Nous allons commencer dans trois, deux, un… maintenant !",
  "LNG-157": "Le numéro du dossier est 2026-07-184.",
  "LNG-158": "Entre vingt-cinq et trente personnes peuvent entrer dans cette salle.",
  "LNG-159": "La mesure indique 0,05 litre.",
  "LNG-160": "La réservation du 21 décembre est à 19 h 15 et coûte 45 euros.",
  "LNG-161": "Chantal Mbuyi vous accueillera à l’entrée.",
  "LNG-162": "Patrick Ilunga a envoyé sa lettre.",
  "LNG-163": "Mado Nsimba rencontrera Serge Kasongo.",
  "LNG-164": "José Manuel vient de Madrid.",
  "LNG-165": "François Noël est arrivé avant midi.",
  "LNG-166": "Aïcha Ben Salah attend à l’accueil.",
  "LNG-167": "Zhang Wei a répondu à l’e-mail.",
  "LNG-168": "Nguyễn An fera une courte présentation.",
  "LNG-169": "Fatou Ndiaye préside la réunion.",
  "LNG-170": "Le docteur Mukendi vous recevra dans l’après-midi.",
  "LNG-171": "Le colis sera envoyé au 120, avenue Kasa-Vubu, à Kinshasa.",
  "LNG-172": "La réunion a lieu au numéro 45 du boulevard du 30 Juin.",
  "LNG-173": "Envoyez la lettre au 16, rue de la Loi, à Bruxelles.",
  "LNG-174": "Envoyez la réponse à info arobase lingala point example.",
  "LNG-175": "Toutes les informations sont sur www point example point cd.",
  "LNG-176": "Elle retournera demain en République démocratique du Congo.",
  "LNG-177": "Le bateau va de Matadi à Boma.",
  "LNG-178": "Jean-Pierre Kalala vous appellera ce soir.",
  "LNG-179": "Le dossier est au nom de A. Bolamba.",
  "LNG-180": "Appelez Clarisse, Joël et Grâce avant le début de la réunion.",
  "LNG-181": "Veuillez m’envoyer la facture par e-mail.",
  "LNG-182": "La réunion commencera à neuf heures précises.",
  "LNG-183": "Le client dit que sa commande est en retard.",
  "LNG-184": "Je voudrais un rendez-vous pour demain.",
  "LNG-185": "Vous devez mettre l’application à jour.",
  "LNG-186": "Ne donnez votre mot de passe à personne.",
  "LNG-187": "La connexion est instable ; essayez de désactiver puis de réactiver le Wi-Fi.",
  "LNG-188": "Le responsable veut que le rapport soit prêt avant midi.",
  "LNG-189": "Vous pouvez payer par carte bancaire ou en espèces.",
  "LNG-190": "Il a dit : « Je suis désolé », puis il a raccroché.",
  "LNG-191": "Le document est joint au message.",
  "LNG-192": "Ce week-end, nous irons rendre visite à la famille.",
  "LNG-193": "Pourquoi as-tu envoyé un message sans expliquer le problème ?",
  "LNG-194": "Le directeur n’est pas au bureau ; il reviendra plus tard.",
  "LNG-195": "Téléversez le fichier, puis appuyez sur le bouton Envoyer.",
  "LNG-196": "Notre vol est annulé à cause du mauvais temps.",
  "LNG-197": "Pour plus d’informations, appelez le service clientèle.",
  "LNG-198": "Activez le Bluetooth pour que le casque puisse se connecter au téléphone.",
  "LNG-199": "Si la connexion au compte échoue, cliquez sur « Mot de passe oublié ».",
  "LNG-200": "Lors de la réunion de demain, nous examinerons le budget, le calendrier de lancement et les commentaires envoyés par les clients.",
};
